"""
Read snakefood dependencies and output a visual graph.
"""
# This file is part of the Snakefood open source package.
# See http://furius.ca/snakefood/ for licensing details.

import jinja2

template = jinja2.Template(
    """
# This file was generated by 1.

strict digraph "dependencies" {
    graph [
        {%- for key, value in graph_config.items() %}
            {{key}}="{{value}}"{% if not loop.last %},{% endif %}
        {%- endfor %}
        ]
    
       node [
        {%- for key, value in node_config.items() %}
            {{key}}={{value}}
        {%- endfor %}
       ];
    
{%- for edge in edges %}
    "{{edge.source}}" -> "{{edge.dist}}"
{%- endfor %}
}

"""
)

graph_config = {
    "rankdir": "LR",
    "overlap": "scale",
    "ratio": "fill",
    "fontsize": "16",
    'dpi': '150',
    "clusterrank": "local",
}
node_config = {
    'fontsize': 14,
    'shape': "ellipse",
    'fontname': "Consolas",
}


def graph(pairs, fontsize=14):
    edges = []
    for key, value in pairs:
        if value:
            for v in value:
                edges.append({'source': v, 'dist': key})
    return template.render(
        graph_config=graph_config,
        node_config=node_config,
        edges=edges,
    )
