name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python: [ "3.8", "3.9", "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - uses: trim21/setup-poetry@dist/v1

      - uses: trim21/install-poetry-project@dist/v1

      - name: test
        run: coverage run -m pytest

      - uses: codecov/codecov-action@v3
